### ISSUE TITLE
Browser pop-up

### ISSUE THREAD

**Issue by cchorun** [MicrosoftDocs/appcenter-docs#1037]
How do I know whether an app is on public or private track? I have a public download link, but it still pops up a prompt to authenticate to App Center. It says "&lt;Build file name&gt; wants to use appcenter.ms to sign in" with Cancel and Continue options. This is confusing for users in that it's not using the app name and no users are creating accounts because it's public. Can any of this be customized?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc4748f-3820-3b4d-b6d5-f0566063ce30
* Version Independent ID: 103d8b55-8719-dcaa-0670-d22e46e328cb
* Content: [Enable In-app Updates - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/inappupdates#feedback)
* Content Source: [docs/distribution/inappupdates.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/inappupdates.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by AnastasiaKubova** [comment]
Since App Center SDK of version `3.0.0` by default Distribute module uses a public distribution group. If you use the private group you have to use `UpdateTrack.PRIVATE` and in this case a user should authenticate. See more [here](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#use-private-distribution-group).

The type of group (public or private) you can choose when creating a Distribution group using the `Allow public access` setting on the Portal. If you select a public group, then after creation will appear note Public near the group name. See more [here](https://docs.microsoft.com/en-us/appcenter/distribution/groups#public-distribution-groups).
