### ISSUE TITLE
Maximum number of members for each app release: 2,000 members block Office dogfood scenarios

### ISSUE THREAD

**Issue by cynlau2020** [MicrosoftDocs/appcenter-docs#1138]
[Enter feedback here]  This new limit setting is blocking Microsoft Office dogfood scenarios (iOS and Android) with this error: Maximum group member amount of 2000 reached.  Can we get exemption?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 753feb24-6869-bdbf-0880-1b5ae52732e0
* Version Independent ID: 8e4db4a1-07c2-ae46-3843-b139f19c1fb1
* Content: [Platform limits for App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/platform-limits#feedback)
* Content Source: [docs/general/platform-limits.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-limits.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Thanks for filing this! We process updates to docs here, to request an exemption you can open a support ticket by going to **https://www.appcenter.ms > ? > Contact Support**

Also, do you know what limit above 2000 would be sufficient? Because I recommend including that as well (whether you have a definite number, or just an estimate.) Knowing the actual number required might save a bit of time in determining if we can do it + potentially activating it.
