### ISSUE TITLE
Android Espresso + AppCenter: Automatic rerun of failed tests

### ISSUE THREAD

**Issue by hs-mzaretski** [MicrosoftDocs/appcenter-docs#1145]
I didn't find any information about possibility to automatically rerun failed tests. Is it possible to set up this for Android Instrumentation tests on Espresso? For example we have 10 tests in our test run and 2 of them are failed. Is it possible to setup automatic rerun of these 2 failed tests. Is it possible to set up number of rerun attempts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d8bdce-a2ad-80cb-efdb-74c0bb3ebb8c
* Version Independent ID: b8d0b4a7-a6b0-42d6-aab3-58a9d8681502
* Content: [Preparing Espresso Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/espresso/)
* Content Source: [docs/test-cloud/frameworks/espresso/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/espresso/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
App Center Test doesn't have built-in support for automatic rerun of tests. 

I couldn't determine for certain if Espresso has built-in support for that either, most of the results I found seemed to indicate it was possible, but it doesn't seem like it's leveraging an explicit rerun feature: https://medium.com/@AndreSand/retry-testrule-for-android-espresso-tests-74683ee3b845

A framework built-in feature for automatic reruns would almost certainly not work, because of how Test operates. But, a custom solution _might_ be possible, depending on the approach tried. Basically, certain interpretations of "automatic reruns" might not violate how the system is designed.

There'd be some serious obstacles though:
- Any screenshots taken during the test shouldn't be manually renamed, deleted, or moved...doing so causes breakages in the final report. 
- If you test on more than one device, you could see a test report that is very messy and verbose due to devices falling out of sequence over the course of the run. (e.g. 3 devices end up running 2 tests normally, while two more end up doing some reruns...the system can't rectify those directly so devices are shown as "skipping" in places.)
- Any approach you use can't exceed available time limits: https://docs.microsoft.com/en-us/appcenter/test-cloud/troubleshooting/time-outs

**Comment by King-of-Spades** [comment]
Based on my findings, I don't think this is something we should cover or mention in our own docs, unless there is evidence that Espresso has built-in feature support for automatic reruns...in which case we should note our own limitation due to it differing from the nominal feature set.
