### ISSUE TITLE
Does Xamarin Test Cloud provide the ability to test applications for MacOS, iOS, etc. apps without the app being developed in Xamarin?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/appcenter-docs#1177]
Does Xamarin Test Cloud provide the ability to test applications for MacOS, iOS, etc. apps without the app being developed in Xamarin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Hi, so the doc you were reading on was for the distribution page, which is referring to distributing apps to testers, rather than testing in App Center Test itself (formerly Xamarin Test Cloud). 

App Center Test supports Android and iOS testing using any of our supported testing frameworks: 
https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/

Strictly speaking, whether or not it's supported is inherited from the testing framework, for example, XCUITest only supports native iOS apps, but Appium supports multiple app frameworks. (Technically including Xamarin, but it's more common to just use Xamarin.UITest for Xamarin apps.)  

You can view a more general support chart of all App Center services here: 
https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix

**Comment by Anand-Moghe** [comment]
@King-of-Spades Thanks a lot!
