### ISSUE TITLE
I'm building a Xamarin Forms app...

### ISSUE THREAD

**Issue by jackbond** [MicrosoftDocs/appcenter-docs#1184]
and someone decided that I should have to write post-clone, pre-build app center scripts in BASH?????

Seriously? Powershell is literally running on the machine. You guys are aware that Powershell is cross platform now right? It's only been that way FOR YEARS.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50588e-c8ad-2b8e-683f-bc5fc612dfe4
* Version Independent ID: 5d9513bd-d179-eaeb-96aa-06bd5ba0224f
* Content: [Build Scripts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/)
* Content Source: [docs/build/custom/scripts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/scripts/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Unfortunately App Center Build doesn't directly support Powershell for non-UWP apps. The build scripts are auto-detected and run by our system based on the filename convention described in the guide. Maybe it's possible to make the build script trigger your desired PowerShell script, so that the only thing you have to write in Bash is pointing to the desired script? 

Since it's not something we support though, I can't document or QA it at this time.

**Comment by jackbond** [comment]
How does one contact the team / individual responsible for the underlying decision?

**Comment by King-of-Spades** [comment]
@jackbond sorry for the delayed response, there were some internal guidance updates I had to confirm. 
This repository: https://github.com/microsoft/appcenter#planning discusses feature requests. As that section of the readme notes, currently App Center is focused on stability and reliability for the time being.
