### ISSUE TITLE
Clarify the platform support of net5.0-windows10.0.17763 NuGet packages

### ISSUE THREAD

**Issue by mattico** [MicrosoftDocs/appcenter-docs#1312]
The net5.0-windows10.0.17763 versions of the NuGet packages are [only supported for use in WinUI packages](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1589#issuecomment-968889264). The getting started guide should mention this. Non-WinUI projects could automatically depend on this version depending on their TargetFramework, causing the analytics to stop working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e799e45-8feb-d74c-4e25-3bdf49301766
* Version Independent ID: b6aef403-76f7-5df2-aa5d-3ed66397893d
* Content: [Get Started with WPF/WinForms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms)
* Content Source: [docs/sdk/getting-started/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/wpf-winforms.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Please pay attention that our docs for the `WPF/WinForms` applications [mention only platforms](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms#1-prerequisites) which we currently support. This platform doesn't mention in docs for `WPF/WinForms` because currently the App Center SDK doesn't support this platform for these applications, only for UWP apps (please see [docs](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp#1-prerequisites)).

I'm closing this issue, but feel free to reopen if you will have additional questions.
