### ISSUE TITLE
https://appcenter.ms can not open，I can not see Analytics and Crashes info

### ISSUE THREAD

**Issue by 0811002321** [MicrosoftDocs/appcenter-docs#1319]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Did you try to open this link via another browser, change the internet connection or use VPN? Does it help you? What error do you get when opening the https://appcenter.ms link?

**Comment by 0811002321** [comment]
I am in Beijing, China, and I can’t use Safari or Chrome opening the https://appcenter.ms link.It was OK before, but now it can’t be opened.

**Comment by 0811002321** [comment]
![截屏2021-12-10 下午3 33 09](https://user-images.githubusercontent.com/3622260/145535258-9a702d6a-9fc3-4560-9e79-87890b5387d3.png)
![截屏2021-12-10 下午3 33 15](https://user-images.githubusercontent.com/3622260/145535287-23dc8696-d6e4-4d9d-bb28-899d04d113a4.png)

**Comment by wisdeom** [comment]
Hi there, I recommend capturing your network traffic using Burp Suite/Network Monitor/Wireshark to isolate the issue better here. I'm under the impression your local network is blocking you to access the App Center portal. Check with your network administrator if there's a proxy server or rules blocking you to access certain URIs. 

Otherwise, there's a known issue in China region, for some of Analytics and Diagnostics SDK data may experience significant delay or not make it to our servers based in the United States. This is due to country specific policies and laws, and our hands are pretty tied to this matter that we cannot guarantee that App Center works in all countries. Please check this doc to find more information. 

https://docs.microsoft.com/en-us/appcenter/general/app-center-security#data-residency-and-sovereignty
