### ISSUE TITLE
ANDROID : react-native link

### ISSUE THREAD

**Issue by doronnahum** [MicrosoftDocs/appcenter-docs#174]
missing  
    compile project(':react-native-code-push')
    compile project(':appcenter-crashes')
    compile project(':appcenter-analytics')
after run link command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by doronnahum** [comment]
It can be helpful if you can add manually install to your docs and link to your example project https://github.com/Microsoft/appcenter-sampleapp-react-native

**Comment by dhei** [comment]
Hey,  `react-native link` should automatically inject these 3 lines into your app/build.gradle so you don't need to manually add them. If you still have this problem, can you share with us a repro step with the output of `react-native info` and the version of appcenter/codepush sdk. Thanks.

**Comment by jwargo** [comment]
@doronnahum `react-native link` doesn't give us many problems on Android, so that's why we don't provide manual instructions. For now, lets treat any issues you have as support issues, and if we see a trend indicating that we need manual instructions, we'll add them.  

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
