### ISSUE TITLE
Appcenter Android Kotlin integration

### ISSUE THREAD

**Issue by freeknortier** [MicrosoftDocs/appcenter-docs#208]
The documentation does not show how to integrate app center into an Android Kotlin based mobile application. If app center is compatible with Kotlin please provide documentation and if not please state that it is not compatible with Kotlin.

**Comment by jwargo** [comment]
@freeknortier everything I've read says that Kotlin and Java are interchangeable, that there's nothing special to use a Java library in a Kotlin app. I've asked the SDK team to respond, but I don't think there's anything else they'll say.

**Comment by iamclement** [comment]
Yes the SDK can be used from Kotlin: https://github.com/Microsoft/AppCenter-SDK-Android/issues/748#issuecomment-402821534.
It's not yet documented and we don't have any ETA on when Kotlin will be available in our documentation. But until then the java code snippet from the doc should work since copy-pasting java code to a Kotlin app automatically turns the code to Kotlin code.
