### ISSUE TITLE
Android Test Orchestrator

### ISSUE THREAD

**Issue by daniel-varela** [MicrosoftDocs/appcenter-docs#268]
It would be nice to add a note about the configuration for Android Test Orchestrator Tests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28fe6afc-06ad-8465-f29a-04b2a118a378
* Version Independent ID: 73b3398b-23b8-230d-d296-8900e053096a
* Content: [Preparing Espresso Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/espresso)
* Content Source: [docs/test-cloud/preparing-for-upload/espresso.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/espresso.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@daniel-varela I will pass the feedback on to the PM team.

**Comment by daniel-varela** [comment]
Thank you @jwargo

**Comment by glennwester** [comment]
@daniel-varela Thanks for writing in! I'm the PM for App Center Test. Support for Android Test Orchestrator is something that we hope to add soon, it's on our roadmap. I will provide an update as it becomes available.

**Comment by gunt0001** [comment]
~~@daniel-varela~~ @glennwester We are in the process to scale up our Android testing on the App Center device farm with Espresso tests. We have seen on various occasions that test runs can completely crash midway through the run due to a problem on a particular device. When this happens we don't get access to the test results that had already completed, nor does the run continue on devices that still need to run. Test runs not being resilient to these type of crashes really impacts our ability to test effectively on App Center with Espresso tests. I think support for the Android Test Orchestrator would be a way to increase crash resilience. It would be great if we could leverage the Android Test Orchestrator on App Center soon.

**Comment by ksmahesh** [comment]
@glennwester 
Thank you for your reply. Great to know that its on your roadmap. 
This is blocking our team from leveraging appcenter for testing purposes. 
It is highly desirable to be able to run these tests on real devices, instead of just emulators. 
Looking forward to test orchestrator being enabled.

**Comment by Saransh-Sharma** [comment]
No Android Test Orchestrator support is a deal breaker for me. When is this support expected?

**Comment by glennwester** [comment]
Thank you for this feedback @Saransh-Sharma! I don’t have a timeline for this support yet, I’ll update here when I can share this.

**Comment by ksmahesh** [comment]
hey @glennwester is android test orchestrator not in your roadmap anymore? I was given a response of "This feature is not in our [roadmap](https://docs.microsoft.com/en-us/appcenter/general/roadmap)." by one of the appcenter support folks. Can you please clarify? We do not want to wait for a feature that might never arrive. Thank you.

**Comment by glennwester** [comment]
Hi @ksmahesh, this is on our radar however I don't yet have a timeline to share. @Oddj0b will be able to speak more to this.
