### ISSUE TITLE
C# Build "Language version: Latest Minor Version" not Honored (at least for UWP builds)

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/appcenter-docs#292]
Should Document: Setting the C# Build Language Version to "Latest Minor Version" does not appear to be honored by AppCenter builds. I was receiving complaints about "default literal" not be valid for C#7.0, specify C#7.1, when my setting was "Latest Minor Version" (which works fine on VS).  I explicitly set all configurations for all platforms to C#7.3 and AppCenter builds stop complaining.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2ace35-a6ef-349a-e009-ca55e3778602
* Version Independent ID: 85a92e95-828a-54f8-b7e7-4f86b8e76abc
* Content: [Configure a C# UWP app in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/windows/uwp/first-build)
* Content Source: [docs/build/windows/uwp/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/windows/uwp/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@kburgoyne I'll have the SDK team take a look.

**Comment by elamalani** [comment]
@jwargo It is related to App Center Build.

**Comment by nilofer** [comment]
Hi @kburgoyne, this seems like something our support can help investigate rather than a docs issue. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. Feel free to open up a conversation with support from our portal regarding this. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/getting-help-with-app-center).
