### ISSUE TITLE
Release a Gradle plugin to upload builds

### ISSUE THREAD

**Issue by frmz** [MicrosoftDocs/appcenter-docs#364]
Hockey had a very nice plugin to upload builds automatically (https://github.com/x2on/gradle-hockeyapp-plugin), it would be great to have the same capability here. I know community might develop something and i know we can get it working using the API and a custom Gradle task but a plugin would make a lot of sense along with the other Gradle components already provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@frmz that's a great suggestion. Can I get you to post suggestions through our support team rather than the docs? The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. There's no facility here to capture feature suggestions. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by frmz** [comment]
Off course, thanks!
