### ISSUE TITLE
Pay-as-you-go

### ISSUE THREAD

**Issue by Norfeldt** [MicrosoftDocs/appcenter-docs#370]
Seems a bit confusing with the pricing. Would be nice if you could turn a knob when you need turbo and superpowers.

Does 1x build pipeline (free tier) mean that I have to choose between iOS and Android?

I'm doing react native so would like do both..

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: bdc863ba-5295-2db8-b37f-584e662e725a
* Version Independent ID: db2a1468-e4fa-6c55-985f-616de1e6484f
* Content: [App Center Pricing Information - Visual Studio App Center](https://docs.microsoft.com/da-dk/appcenter/general/pricing)
* Content Source: [docs/general/pricing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/pricing.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by maestersid** [comment]
Hi @Norfeldt 

We opted for sliders instead of knobs with pricing, though I like the idea of being able to take it to 11 ;).

More seriously, concurrency is applied to all apps within a given org or account, regardless of platform. So with your scenario, if you configure build for both your android and iOS apps and commit an update to both, it will build one then the other.
