### ISSUE TITLE
App center export documentation

### ISSUE THREAD

**Issue by jzeferino** [MicrosoftDocs/appcenter-docs#387]
I Was reading thought the docs on how to export analytics.

[In this topic](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/export.md#export-crashes-attachments-and-errors) is mentioned the `blob_path_format_kind` but I can't find it documented in the [App Center API](https://openapi.appcenter.ms/#/export/ExportConfigurations_Create).

Need some clarification on this.

**Comment by jwargo** [comment]
@jzeferino I'll have the team take a look at making a docs update for this, thanks for bringing it to our attention. In the mean time, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by nikitag-ms** [comment]
@jzeferino, thank you for pointing this out. We will fix the documentation, but I wanted to give you an update before it happens so that you have an idea what the property is about.

`blob_path_format_kind` can have two values: `WithAppId` and `WithoutAppId`. These allow you to configure the naming convention of blobs that App Center exports to your storage account.

- When `blob_path_format_kind = WithAppId`, then your client logs get exported to your storage account under `@"{yourAppId}/{year}/{month}/{day}/{hour}/{minute}"` path
- When `blob_path_format_kind = WithoutAppId`, then your client logs get exported to your storage account under `@"{year}/{month}/{day}/{hour}/{minute}"` path

Essentially, this allows you to specify whether `{yourAppId}` will be added to the path of the destination blobs or not. This is helpful if you export logs from multiple apps into the same storage account and keeps them separate.

Let me know if I can provide more information.
