### ISSUE TITLE
What about React Native? Are these env variables available in Javascript too?

### ISSUE THREAD

**Issue by sanjaypojo** [MicrosoftDocs/appcenter-docs#430]
Can we access these env variables in javascript? Is it available at bundle creation? For example, if we set a variable called STAGE as 'development' in the AppCenter, is that equivalent to `STAGE=development react-native start`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f3af3f-ef07-8896-4b3c-05cef163b51a
* Version Independent ID: b4b1f6a4-5975-358b-1cf4-f7b10a2245cd
* Content: [Environment Variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/)
* Content Source: [docs/build/custom/variables/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/variables/index.md)
* Service: **mobile-center**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by jwargo** [comment]
@sanjaypojo they're build system environment variables, environment variables on the computer system executing your build. I'm not an expert, but as I understand it, if you're running a node script, then those environment variables are available to it (because they're environment variables and node offers a method to read them from the system running the node script). I don't think you can execute node scripts as your build scripts, but there's no reason (that I know of) that you can't execute a node script from a powershell or bash script. 

Anyway, I've added the PM to this issue for a second opinion. Also, please keep in mind that the comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by khanmubaris** [comment]
How do you access these environment variables in javascript?
