### ISSUE TITLE
The documentation on how getErrorAttachments works and what it expects is not clear

### ISSUE THREAD

**Issue by Eyesonly88** [MicrosoftDocs/appcenter-docs#446]
The documentation mentions being able to attach text files and binary files. 
However, what if we don't have files at all? which arguments are required?

`ErrorAttachmentLog.attachmentWithText('bla', null) // is this allowed?`

`ErrorAttachmentLog.attachmentWithText(null, 'data.text') // is this allowed?`

- Also, what is the structure of the `report` object? what does it look like?
- Are we allowed to do API calls in this function? example a webhook call?
- Same question with images, what if I have a base64 image only without filePath, can I just pass the first parameter?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* Content: [App Center Crashes for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native)
* Content Source: [docs/sdk/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by guperrot** [comment]
# Attachment parameters

The text content or base64 content for binaries is required, the file name is optional (it's used only by the portal to list attachments on the report and allow downloading with that file name).

# Attachment callback

The documentation has an example for async syntax where you can do long running operations, this won't block the UI or the SDK processing to use this pattern. The doc example returns an inlined promise.

# ErrorReport

The report object is dynamic and we didn't want to clutter the docs with all the fields especially since there are platform differences for the React Native SDK.

Here is a typescript schema of the report object: https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/appcenter-crashes/Crashes.d.ts#L44

The id is a unique guid for this specific occurrence of the crash.
iOS will have only signal and exceptionReason while on Android exception will be the stack trace.
appErrorTime and appStartTime are timestamps in miliseconds since epoch, for Android there is an issue where the type is string instead of number.

**Comment by Eyesonly88** [comment]
For future readers, making the second parameter optional was fixed in version 1.10.0 (https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.10.0). 

Therefore, previous versions require the second parameter.
