### ISSUE TITLE
App Center API Swagger Issue

### ISSUE THREAD

**Issue by ShaneQi** [MicrosoftDocs/appcenter-docs#477]
In this POST endpoint, it doesn't show an example of the request body. If I click 'try it out', it won't show the field of the request body, either.

https://openapi.appcenter.ms/#/build/branchConfigurations_create

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by amchew** [comment]
Thanks a lot for letting us know @ShaneQi ! 
I'll chat with the team to edit this.

**Comment by nilofer** [comment]
Hi @ShaneQi, thanks for bringing this to our attention. The team will get this fixed so this endpoint shows a request body.

**Comment by dennispan** [comment]
@ShaneQi We've deployed a change that adds swagger for creating branch configuration API. Thanks for reaching out!

Unfortunately, due to limitation in swagger and the complexity of the models in this API, we were not able to make it clear that which properties are required. They really depend on the OS and platform of your application, and whether you have signing enabled, etc. To have a more accurate idea of how to use the API, I would highly encourage use browser debugger trace the API details from the portal, when you save a build config. They copy paste that as a starting point.

**Comment by ShaneQi** [comment]
@DennisPan 
I do see that the body field now showing up 🎉.

The reason that the model can't be represented in swagger makes sense to me. And the solution works for me.

Thanks for following through with this issue.
