### ISSUE TITLE
Distribution Group Button is missing 

### ISSUE THREAD

**Issue by ClaraLaMa** [MicrosoftDocs/appcenter-docs#480]
Hi, my organization was imported from hockeyApp to MS appcenter. Now picking my organization and the "people"-button the "Distribution Groups"-button is missing. Creating a new organization in MS appcenter the button exists but in the imported app is doesn't. It woud be nice to have a consistent menu in my organizations. Can you fix this please? Thanks!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5a807b36-339c-dd76-a6bb-132005991516
* Version Independent ID: 8ffb33e3-09fd-fe41-742f-a9f4d11bf901
* Content: [Manage App Center Distribution Groups - Visual Studio App Center](https://docs.microsoft.com/de-de/appcenter/distribution/groups)
* Content Source: [docs/distribution/groups.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/groups.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by m2u-84** [comment]
Indeed this issue is very irritating. Below I have attached a comparison of the current situation:

![comparison](https://user-images.githubusercontent.com/11140006/53343181-0a810b80-3910-11e9-9833-0168cf5c32c1.jpg)

We had to create a new organization to find out that this functionality is indeed missing for migrated organizations. Also, the instructions are rather misguiding: “On the People page, click the distribution group link to open the shared distribution groups page.” The described workflow doesn’t seem to be implemented (yet?).

In general it would be very helpful if all pages of the documentation stated cleary if this functionality is available yet and if so if it applies to both “App Center-exclusive” and migrated organizations.

**Comment by jwargo** [comment]
@ClaraLaMa The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

We also recently started publishing our roadmap and collecting customer feature requests here: https://github.com/Microsoft/appcenter.

**Comment by m2u-84** [comment]
> The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs.

That’s what I tried to do in my comment above:

> Also, the instructions are rather misguiding: “On the People page, click the distribution group link to open the shared distribution groups page.” The described workflow doesn’t seem to be implemented (yet?).
> In general it would be very helpful if all pages of the documentation stated cleary if this functionality is available yet and if so if it applies to both “App Center-exclusive” and migrated organizations.

Could you please clarify why these steps don’t seem to be accurate? Did I miss something? Is it due to the migration scenario? (Please refer to my screenshot above.)

Thanks in advance!
