### ISSUE TITLE
No forums support!

### ISSUE THREAD

**Issue by JarrydSemmens** [MicrosoftDocs/appcenter-docs#526]
There is nowhere I can ask questions for support for App Center.
There are issues I cannot solve without help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center#feedback)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by jwargo** [comment]
@JarrydSemmens that is not true, on EVERY App Center page, there's a blue chat button on the bottom-right corner that connects you **directly** to our dedicated support team. It couldn't be any easier. You can read more here: https://intercom.help/appcenter/getting-started/getting-help-with-app-center

**Comment by stephenhauck** [comment]
@jwargo  The chat no longer exists ... 8 hours to get back to you is not good 
Now it seems you can't build MAUI in Appcenter because all I did was switch to use https://www.nuget.org/packages/CommunityToolkit.Mvvm  and C# 9 with source generators and after 3 days I have no answer as to why it doesn't work now ...

I will now delete all my moficications and code optimizations because Microsoft is not "really" supporting Appcenter.

I love Appcenter, if MS is killing it fine but then give me step by step instructions on how to move to Azure pipelines since I don't know Azure and don't want to ....

Do something ... Roslyn 4 has been out for like 2 years .. why is it not part of the Appcenter build yet ?

**Comment by stephenhauck** [comment]
For anyone looking this may be the best information on migrating but again .. I don't want to leave Appcenter because Microsoft says it's not deprecated ....

https://devblogs.microsoft.com/dotnet/devops-for-dotnet-maui/

If anyone has any better information like .. pre build scripts for Appcenter that work ????
