### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by candelinJC** [MicrosoftDocs/appcenter-docs#554]
Regarding the line
"From your home screen or menu, tap on Settings&gt;Security. Under the Device Administration heading, check the box next to Unknown Sources."
does not follow my menus on my Pixel Gen 1 running Android 9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcecd38a-7696-e7f8-853d-d3c12c0b050c
* Version Independent ID: abdba972-b2cd-6c73-83fe-bb1abaac190f
* Content: [Testing Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android#feedback)
* Content Source: [docs/distribution/testers/testing-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-android.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@candelinJC yeah, sorry about that, but settings move around.

**Comment by jwargo** [comment]
@candelinJC Google changed the security model in Android 9, so that setting is no longer needed. You can read about the changes [here](https://www.zdnet.com/article/android-oreo-google-has-just-made-app-installs-from-unknown-sources-a-lot-safer/).  I'm not an expert on Test, so I don't have specific instructions to give you, but I've asked the PM to take a look at making a doc update.

**Comment by jwargo** [comment]
Closing due to no response from the customer
