### ISSUE TITLE
Push notifications not received on iOS when device was off

### ISSUE THREAD

**Issue by christopheph** [MicrosoftDocs/appcenter-docs#575]
Hi,

It seems that push notifications are not recieved by iOS devices that where offline at the moment of the push notification sending (even some seconds). If we go to appcenter push notification page, the notification is marked to sent 1/1 even if device never recieved it.

We are using a xamarin app, and notifications are well received when device is online even if the application is not running

Thank you for your feedback.

**Comment by jwargo** [comment]
@christopheph you have to setup your app to process background notifications. See https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app

**Comment by christopheph** [comment]
Hi @jwargo we tested the functionnality, in fatc using the "silent push" feture of AppCenter but this does not solve our problem.

I will try to explain the use case we try to achive:

1. The device is offline (disconnected from the network) or off (shutdown)
2. A push notification is sent when device is not connected
3. The device is connected again (network reconnection or on again), the notification should be recieved by the device ==> wich is not the case. Appcenter indicates the notification is sent but notification is never recieved.

By reading some apple documentation, we are wondering if it is not because the apns-expiration value is not send or has a wrong value. Is there a way to sent it right or is there a bug in appcenter ?

Thank you in advance for your answer.

**Comment by jwargo** [comment]
@christopheph I apologize for the delay in my response, I was out of the country for two weeks. I know there's no guarantee that a notification will be sent if the device is off when it's sent. I imagine this is because of the `expiration` value, but I'm not an expert. The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. You'll get the best help from our support team. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
