### ISSUE TITLE
Followed the guide, I see no analytics data. Help?

### ISSUE THREAD

**Issue by fermelone** [MicrosoftDocs/appcenter-docs#582]
Also not sure why I am redirected to a page with no content! (this one).

I followed the steps for an iOS build on Unity 2019.1.5f1, and all the SDKs are installed ok, App Center Behavior game object is ok and it is there when running the game. Still, no data shown back in appcenter.

Help!

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64bf6eee-8421-34eb-a50e-78132fa8d45f
* Version Independent ID: 99cb3da9-7d74-8648-a438-de3849bd6a2c
* Content: [Unity SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/unity#feedback)
* Content Source: [docs/sdk/troubleshooting/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/unity.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by jwargo** [comment]
@fermelone that's because we wanted to publish troubleshooting information, but don't have any yet. When we have some, we'll add it to the page. 

If you're having trouble making something work, please open an issue with our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
