### ISSUE TITLE
Where to put the google-services.json file

### ISSUE THREAD

**Issue by LanderVe** [MicrosoftDocs/appcenter-docs#679]
"4. Copy this file to your Android project app module."
This only applies to Android Native projects, not to Xamarin. Is this thread correct? https://stackoverflow.com/questions/33435552/where-can-i-add-google-services-json-in-xamarin-app 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed528dcd-ecaf-697e-c64a-30651d26ff3d
* Version Independent ID: 1e92bbb4-5800-6d31-51ee-c6d5864801d1
* Content: [App Center Push for Xamarin.Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android)
* Content Source: [docs/sdk/push/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by LanderVe** [comment]
Ok, I hadn't read the rest of the article yet. Later on it is described properly.

**Comment by anywherepilot** [comment]
The prerequisite is only to download the file, and store it *somewhere*. The reason the sentence isn't a bit more clear is that this is an inlined version of the documentation for getting started with Android native projects. Since the details about what to do with the file are below, as you already discovered, I will close this issue now.
