### ISSUE TITLE
App center distribute task: no existing service connections of the appropriate type could be found

### ISSUE THREAD

**Issue by li2** [MicrosoftDocs/appcenter-docs#740]
Doc is out of date, the screenshot in doc has a `+` button to create a service connection,
![image](https://user-images.githubusercontent.com/6058601/65662963-eab5ef80-e078-11e9-8cc3-286233797314.png)

However, it doesn't have such `+` and always tells me `no existing service connections` when I tried to add App center distribute task to the pipeline:
![image](https://user-images.githubusercontent.com/6058601/65662992-fc979280-e078-11e9-925b-85cf65148861.png)

I stuck on it for a few hours, finally, I found this doc to add a new **App Center service connection**
https://docs.microsoft.com/en-au/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#create-a-service-connection

Please update the doc, thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28aa9747-f64a-d886-487d-8ebb97d717b8
* Version Independent ID: 0c7edbb7-4bf7-f66c-c8a7-275308365f27
* Content: [Deploy Azure DevOps Builds with App Center - Visual Studio App Center](https://docs.microsoft.com/en-au/appcenter/distribution/vsts-deploy)
* Content Source: [docs/distribution/vsts-deploy.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/vsts-deploy.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by anywherepilot** [comment]
Hi @li2. Thank you for noticing the documentation needs an update. This is because you are using the new YAML pipeline editor, while the screenshots are for the classic editor. You can still use the classic editor for new pipelines when you create them, but of course the new editor is the way forward. I will update the documentation with screenshots of the new editor. The way you found for achieving the goal is indeed the way to go!
