### ISSUE TITLE
Moving just app distribution, not CI/builds

### ISSUE THREAD

**Issue by jkotrlik** [MicrosoftDocs/appcenter-docs#741]
Hi, we're using HockeyApp just for distribution purposes - we build the apps elsewhere. For the distribution itself, we're using 2 of HockeyApp's endpoints, first one to create new version and second one to upload the build (.ipa or .apk). So now we wonder how much this will have to change. What we really liked is a possibility to select from multiple builds there, without the need to create new releases and without the annoying spam of emails every time someone creates a PR build. Is this transition going to be easy for us, or will we have to allocate some considerable time to figure out new workflow? Thanks!

**Comment by jkotrlik** [comment]
And just to clarify - I'm talking specifically about distribution to our test users and developers, no Store needed.

**Comment by anywherepilot** [comment]
Hi @jkotrlik 

In App Center you can easily use just Distribution, either through the portal or via the CLI or API.

If you build elsewhere (not using App Center), App Center will not perform any action when you open a PR and will not send any emails.

It is not possible to create multiple releases at once through the portal, but you can automate the creation of releases through the CLI or API. When distributing a release to users and developers, you can choose whether you want to notify them of the release or not.

I hope your transition from HockeyApp to App Center worked out. Since this question is quite old and HockeyApp is no more, I will close the issue. If you have further questions, just comment below or reopen.
