### ISSUE TITLE
Cannot automate Webview (Azure b2c Login Page)

### ISSUE THREAD

**Issue by EugeneKonneh** [MicrosoftDocs/appcenter-docs#748]
I am new to XamarinUITest.
We have decided to use XamarinUI Test to automate our new mobile application.
The application uses an Azure b2c webview login page.

I can use the app.Query to interact with the app prior to loading the login page.
However, once the login page is loaded, it points to a url (xxx.b2clogin.com)
sample code:
<div class="entry-item">
      
![xamarin Code](https://user-images.githubusercontent.com/48555490/66041761-92686d00-e512-11e9-8391-dc7f9b9f2b72.png)
![xamarin test result](https://user-images.githubusercontent.com/48555490/66041762-93010380-e512-11e9-9ba2-d2a863cb4491.png)
![xamarin test](https://user-images.githubusercontent.com/48555490/66041764-93010380-e512-11e9-94a3-55dd421f3768.png)

I gave attached a sample of html, test script and test results..

**Comment by Oddj0b** [comment]
Hi @EugeneKonneh, have you tried using our page for [Working with Web Views](https://docs.microsoft.com/en-gb/appcenter/test-cloud/uitest/working-with-webviews)

**Comment by EugeneKonneh** [comment]
Hi @Oddj0b 
Thank you for your response.
Yes.
I have tried all the queries:
app.Query(c=>c.Class("WKWebView")) and
app.Query(c=>c.WebView()) 
and they both return a ".... gave 0 results."

**Comment by EugeneKonneh** [comment]
A public version of the app can be accessed via this link [MyKeysPro](https://play.google.com/apps/testing/com.dormakaba.mykeyspro)

**Comment by radolo1111** [comment]
07.10.2019 9:36 AM "Villars Gimm" <notifications@github.com> napisał(a):

**Comment by jmoody** [comment]
Please try using the XPATH or JavaScript APIs documented here:

https://docs.microsoft.com/en-gb/appcenter/test-cloud/uitest/working-with-webviews
https://github.com/calabash/calabash-ios/wiki/06-WebView-Support

**Comment by EugeneKonneh** [comment]
Hi @jmoody 
Thank you.
I have tried the recommended with no luck.
Both the XPath and the JavaScript rely on the system locating the WebView.
At the moment, I am not able to identify the Webview as a page, let alone interact with its elements.
Thanks

**Comment by Oddj0b** [comment]
@EugeneKonneh I think the best approach is to close the issue here and if you can contact our support team through https://appcenter.ms that would be best.

**Comment by jmoody** [comment]
@Oddj0b is correct.  I don't follow this repo.

There is a command in Xamarin.UITest called Tree or Dump?  That will show the entire view hierarchy.  That might help you.   Maybe the view is in another UIWindow?

**Comment by EugeneKonneh** [comment]
Update.
I have realised that:
1. The Webview is located outside our app.
2. Xamarin.UITest/Calabash are unable to automate more than one app at a time
3. And it cannot be used to automate system apps such as the browser

Question:
Has anyone come across this? and how did they manage to resolve it?

Thanks for your feedback

**Comment by jmoody** [comment]
Calabash, and to some extent Xamarin.UITest, can probably automate this.

In Calabash, you would use the DeviceAgent APIs.

https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/device_agent.rb

I don't think Xamarin.UITest has an API for interacting with DeviceAgent query routes.

You can explore using DeviceAgent with curl or Postman (or its like).  Run your tests to point of failure and set a breakpoint or binding.pry.  

The DeviceAgent query routes are defined here: 

https://github.com/calabash/DeviceAgent.iOS/blob/develop/Server/Routes/QueryRoutes.m

* 1.0/tree
* 1.0/query

```
# or use IP address of physical device or the Bonjour name: <name of iphone>.local
# in the simulator, use 127.0.0.1
# port number cannot be changed.
http://127.0.0.1:27753/1.0/query
{
  "type" : "Button"
}
```

It is possible that DeviceAgent will not be able to see the window because it is outside the Application Under Test (AUT).  DeviceAgent is capable of automating any app (SpringBoard, Settings, Safari, etc).  DeviceAgent needs to be extended to allow queries to specify which app to interrogate.

**Comment by anywherepilot** [comment]
@EugeneKonneh I hope Joshua's comment above solved your issue. Since this ticket is quite old and I see a recommendation to open a support ticket instead since it is very specific, I'll close this issue now. Feel free to write below or reopen; please consider opening a support case through the App Center portal first.
