### ISSUE TITLE
Would be better if there is an example

### ISSUE THREAD

**Issue by tigerlily777** [MicrosoftDocs/appcenter-docs#773]
Hi, I feel it is a bit confusing to understand well the relationship between the owner/distribution groups/organisation/user. Even with some experience about HockeyApp, I still read a couple of times to understand the description of distributing groups on HockeyApp and AppCenter. It would be much better if there is an example. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65235df-7ae9-6cde-24fe-c570c0191086
* Version Independent ID: 9401ae78-7fc9-e168-db7b-7101b1928cb5
* Content: [Distribute - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/distribution#feedback)
* Content Source: [docs/transition/distribution.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/distribution.md)
* Service: **vs-appcenter**
* GitHub Login: @daadam
* Microsoft Alias: **daadam**

**Comment by dipree** [comment]
@tigerlily777 what kind of example do you have in mind?

**Comment by anywherepilot** [comment]
@tigerlily777 please check the comments in this issue which link to existing documentation describing all these features: https://github.com/MicrosoftDocs/appcenter-docs/issues/739#issuecomment-564883179

Since HockeyApp is no more, and we have docs describing how App Center works, I will close this issue now.
