### ISSUE TITLE
App Center Login issue "Update user profile failed, status code 500, status msg: Internal Server Error"

### ISSUE THREAD

**Issue by yoganandhini23** [MicrosoftDocs/appcenter-docs#774]
Hi ,
I am trying to Setup an Account in App center 
Getting the following error , When I am Using my company Microsoft account : <redacted>

Another Issue is When I click on forget password , I am not getting reset link to my above ID.

**"Update user profile failed, status code 500, status msg: Internal Server Error"**
URL It take me to is :
https://appcenter.ms/sign-in?original_url=/invitations/org/3291163f8ac5f7df77188f3f3211e9f90eb5668b55e6c9a7e99badf23d2c4205?&&&& 

![image](https://user-images.githubusercontent.com/10509007/67278866-c73c6400-f4c1-11e9-8f71-7144690fb4c0.png)

![image](https://user-images.githubusercontent.com/10509007/67279696-6e6dcb00-f4c3-11e9-8fd0-39fee444fcad.png)

**Comment by anywherepilot** [comment]
Hi @yoganandhini23,

This repository is for documentation issues. For issues like this, please contact App Center support, or Microsoft support in general since the sign-in flow is not owned by App Center. Normally you contact support through the website, but you cannot log in, so that won't work. If any of your colleagues already have an account, you could ask one of them to open a support case. Otherwise, please use the general App Center repository: https://github.com/microsoft/appcenter/issues

Always be careful sharing personal information in public spaces. I deleted your email address from the original question.
