### ISSUE TITLE
.dSYM via AppCenter

### ISSUE THREAD

**Issue by iamgerardm** [MicrosoftDocs/appcenter-docs#776]
> If you use the App Center to build and auto distribute your app to your end users, you don't need to manually obtain and upload the symbol files as detailed in the steps above.

The help page specifies the above statement. However, upon viewing the diagnostics it still complains of having no file. How do you get the .dSYM when the build/distribution is handled entirely though the AppCenter?

**Comment by ajaykn** [comment]
Hi @iamgerardm, 
As the documentation says, when build is configured to automatically distribute the build, then App Center also uploads the .dsym file to the Diagnostics section.
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/40024974/77891889-4e6ede80-728f-11ea-8a35-7462c97e490e.png">

This works as expected and since you were mentioning that you are not able to see the symbols in Diagnostics section, it might be some specific case.

Can you please raise a support ticket via blue chat button in App Center and we will take a deep look.
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/40024974/77892183-ce954400-728f-11ea-8add-c483698a31d9.png">
