### ISSUE TITLE
Xcode version / Xamarin SDK version

### ISSUE THREAD

**Issue by tompi** [MicrosoftDocs/appcenter-docs#801]
I assume there are environment variables for these, but cant find any documentation? (I need to log these in out deployment systems, so we can recreate any production builds...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50588e-c8ad-2b8e-683f-bc5fc612dfe4
* Version Independent ID: 5d9513bd-d179-eaeb-96aa-06bd5ba0224f
* Content: [Build Scripts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#feedback)
* Content Source: [docs/build/custom/scripts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/scripts/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by timeyoutakeit** [comment]
Hey @elamalani, do we have documentation to address this?

**Comment by King-of-Spades** [comment]
I'm not aware of any environment variables for those. 

Xcode version can be logged using this command:
> xcodebuild -version

Which shows the active version being used for building. The only way to check the Xamarin version I've found reliably is the Mono version:
> mono --version

@timeyoutakeit if you have any suggestions where it'd be good to place those, let me know. I did an experiment awhile back to try and find a way to report different tooling versions via the command line: https://github.com/King-of-Spades/ACLog/blob/experiment-with-CLI-version-tool/versions.txt

However, it's pretty kludgy.

**Comment by tompi** [comment]
Sure, I managed to script this myself, it just feels like a thing that OUGHT TO be available.

I mean, all the options selected in the build definition(like sdk, xcode version etc) should be available, not just a select few.

E.g. for xamarin android, you select the project you want to build, and this is exposed in the APPCENTER_XAMARIN_PROJECT environment variable.
In the same build definition, two lines down, you select SDK version, but this is NOT available as an environment variable.

P.S. The reason we need these(especially sdk and xcode) is that if you need to do a hotfix, you cant really be sure of what the previous version was built with(since there is no history on changes for build definition) unless you keep track of this(we send a mail with commit-sha, xcode, sdk etc for each build)

**Comment by King-of-Spades** [comment]
@tompi 
> Sure, I managed to script this myself, it just feels like a thing that OUGHT TO be available.

Actually it's been something I've been trying to figure out for a long time. And something about you mentioning it gave me an idea, I figured out the right person to talk to, and it turns out that this command will report all the tooling currently defined in the build image:
> eval cat $HOME/systeminfo.md

The output is essentially equivalent to the documentation here: https://docs.microsoft.com/en-us/appcenter/build/software (once you select macOS version), in fact they're generated the same way. But the advantage is, using that file you can see which tools were active specific to that build. 

I'm working on adding it to documentation too. Now, the catch is; it only lists the image, not the specific build settings you've got configured. I'm trying to find a way to output those as well, so that they're also auditable.

**Comment by King-of-Spades** [comment]
Published this awhile ago, but forgot to close out the issue: https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/build-failed#tracking-changes-in-app-center-cloud-build-machines

**Comment by tompi** [comment]
Great! Thank you.
