### ISSUE TITLE
Explain how to access environment variables

### ISSUE THREAD

**Issue by cocowalla** [MicrosoftDocs/appcenter-docs#812]
The docs state that an environment variable `RUNNING_IN_APP_CENTER` is set to `1` by default, and is accessible in the app.

However, if I use `System.Environment.GetEnvironmentVariable("RUNNING_IN_APP_CENTER")`, it never has a value.

If `System.Environment.GetEnvironmentVariable` cannot be used to obtain environment variables in the app at runtime, the docs should explain how, for both Android and iOS if it differs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01181288-ab5c-4fd5-1d76-3d5dbe61c486
* Version Independent ID: 2aeffa5c-b5b5-cf71-e382-4210e7d10454
* Content: [Environment variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/environment-variables)
* Content Source: [docs/test-cloud/environment-variables.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/environment-variables.md)
* Service: **vs-appcenter**
* GitHub Login: @GlennWilson
* Microsoft Alias: **v-glenw**

**Comment by jmoody** [comment]
We have updated the docs and have a few more clarifications in progress.

In particular, we describe which frameworks support setting application environment variables and which support setting test environment variables.

We also show that on Android, you must use `InstrumentationRegistry.getArguments()` to access `RUNNING_IN_APP_CENTER` because Android does not support environment variables.
