### ISSUE TITLE
Is there anyway to get my keystore file that i upload for signing process?

### ISSUE THREAD

**Issue by amlwin** [MicrosoftDocs/appcenter-docs#863]
I just lost my keystore in my local machine. Fortunately,  I added once my keystore file to appcenter form release process. I still visible that keystore in the dashboard (show in screen shot).  Is there any chance to get my keystore?
![Screen Shot 2019-12-12 at 10 05 20](https://user-images.githubusercontent.com/9652656/70681500-f903c700-1cc9-11ea-8cae-da34da163efa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb88b888-1e68-8a75-efa4-cef2c33d4369
* Version Independent ID: 2fd3c90f-d7e5-5af3-9a50-b5571ac84995
* Content: [Android Code Signing Setup in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/android/code-signing)
* Content Source: [docs/build/android/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/android/code-signing.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by anywherepilot** [comment]
Hi @amlwin. There is no built-in functionality to download back your key store. Please open a support ticket using the button in the lower-right corner of the screen (when no wizard is open). We will see what we can do for you!

There should be no need to get your key store back, because you can just create a new one and sign your app with a new key. Just discuss what with the support team though, in case you have some scenario where you do need it back.

**Comment by nilofer** [comment]
Hey @amlwin, this looks similar to this [issue](https://github.com/microsoft/appcenter/issues/703) in our official non-docs repo. We don't support this today as @jerietve mentioned as signing credentials are securely stored and not made available to you once they've been provided to App Center.
