### ISSUE TITLE
Push instructions appear to be out of date

### ISSUE THREAD

**Issue by johnmackerras** [MicrosoftDocs/appcenter-docs#941]
Twice in this document the line "In the project navigator that opens, select Push." appears, yet when I log onto AppCentre, there is no option for Push within either my Android or my iOS application. Nor does this document explain what you need to do or how to upload the Firebase Server Key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22063c99-5621-e69d-1e28-42970ccc44e5
* Version Independent ID: 9500782b-5db0-45c6-7709-749adb9db35b
* Content: [Configuring the Push Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/service-config#feedback)
* Content Source: [docs/push/service-config.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/service-config.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-push**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@johnmackerras that's because we announced that we're retiring the Push service as described here: https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/. We disabled the Push UI for any apps that do not already have Push configured. As we're retiring the service, it seemed to make sense to only continue to show the Push UI for apps that are currently using the Push service. We don't want users adding Push to a new app since the service will not be available.
