### ISSUE TITLE
Integrate manually on Android

### ISSUE THREAD

**Issue by yogieputra8** [MicrosoftDocs/appcenter-docs#98]
Hi,
Nice documentation, are you guys planning to add support for integrating manually on Android?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment]
@yogieputra8 What do you mean by integrating manually on Android? Integrating what?

**Comment by yogieputra8** [comment]
@jwargo Ah sorry for the missing piece of the information. I was posted this comment in the Documentation page and does not realize that my question will be posted in this Github issue. 

So, as I read this Docs https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native. I want to integrate `appcenter-crash` and `appcenter-analytics` manually to my existing project (Android - React native). But the docs says the manual SDK integration can be applied to iOS only for now. 
Is there any plans for you guys to support SDK manually integration with Android?

**Comment by jwargo** [comment]
@yogieputra8 yep, we publish the docs using GitHub, so all comments come through as issues.  As I understand it, and I'll let @elamalani correct me if I'm wrong, but the manual steps outlined in the docs are for those who don't want to use Cocoapods to add the App Center SDK to an iOS app. This doesn't apply on the Android side, just use the instructions for adding the SDK using the existing tools and you're good.  Is there a reason you don't want to just use the default approach?  It works quite well for adding the SDK to an existing Android app project.

**Comment by elamalani** [comment]
@yogieputra8 Thanks for your feedback. We have manual instructions for iOS because developers might not want to use Cocoapods as a dependency manager for iOS apps. Cocoapods needs to be installed first before adding App Center packages. And that's why we have shared instructions on how to manually add frameworks to your iOS app.

On Android, you don't need to install any dependency manager to add the packages. App Center modules are hosted on JCenter and developers just need to modify their build.gradle file to include the dependencies which is pretty straightforward. That's why we don't have manual integration steps in Android and don't plan to add it the docs at this time.
